plugins:
  - uses:
      - plugin: https://c99e-89-187-180-4.ngrok-free.app
        with:
          disabledCommands: []
          miscellaneous:
            maxConcurrentTasks: 3
        runsOn: ["issue_comment", "issue_comment.created", "issue_comment.edited"]
