plugins:
  - uses:
      - plugin: https://damaged-alysa-moniswap-b2f3cc8b.koyeb.app
        with:
          disabledCommands: []
          miscellaneous:
            maxConcurrentTasks: 3
        runsOn: ["issue_comment", "issue_comment.created", "issue_comment.edited"]
