plugins:
  - uses:
      - plugin: https://normal-evolving-terrier.ngrok-free.app
        with:
          disabledCommands: []
          miscellaneous:
            maxConcurrentTasks: 3
        runsOn: ["issue_comment", "issue_comment.created", "issue_comment.edited"]
